@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList : persons
AddressBook *-right-> "1" UniquePersonList : pinnedPersons
AddressBook *-up-> "1" UniqueTagList
AddressBook *-down-> "1" UniqueEventList
UniqueTagList -[hidden]right-> UniquePersonList

UniqueTagList -right-> "*" Tag
UniquePersonList -right-> Person
UniqueEventList -right-> "*" Event

Person -up-> "*" Tag
Person --> "*" Event

Person *--> "1" Name
Person *--> "1" Phone
Person *--> "0..1" Email
Person *--> "0..1" Address
Person *--> "0..1" Photo
@enduml
