@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":XYZCommand" as Command LOGIC_COLOR
participant "<<utility>>\nCommandUtil" as CommandUtil LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR

end box

[-> Command : execute(model)
activate Command

note right of Command
    XYZCommand represents any command
    that requires target disambiguation
    (e.g., DeleteCommand, EditCommand).
end note

Command -> CommandUtil : targetPerson(model, targetInfo)
activate CommandUtil

CommandUtil -> Model : findPersons(targetInfo)
activate Model
Model --> CommandUtil : matches
deactivate Model

CommandUtil -> CommandUtil : targetPersonFromMatches(model, matches)
activate CommandUtil

alt matches.size() == 1
    deactivate CommandUtil
    CommandUtil --> Command : targetPerson
    deactivate CommandUtil

    [<-- Command : result
    destroy Command

else matches.size() > 1
    activate CommandUtil
    CommandUtil -> Model : showMatchingPersons(matchingPersons)
    activate Model
    Model --> CommandUtil
    deactivate Model


    CommandUtil --> Command : <<exception>> CommandException
    deactivate CommandUtil

    [<-- Command : <<exception>> CommandException
    destroy Command

else matches.size() == 0
    activate CommandUtil

    CommandUtil --> Command : <<exception>> CommandException
    deactivate CommandUtil

    [<-- Command : <<exception>> CommandException
    destroy Command
end

deactivate Command
@enduml
