@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
skinparam classAttributeFontColor #FFFFFF
skinparam classAttributeIconSize 0

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model

Class ModelManager {
    -filteredPersons: FilteredList<Person>
    -sortedPersons: SortedList<Person>
    -filteredEvents: FilteredList<Event>
}

Class AddressBook
Class UserPrefs

Class UniquePersonList {
    -internalList: ObservableList<Person>
}

Class UniqueEventList {
    -internalList: ObservableList<Event>
}

Class I #FFFFFF
}

show ModelManager fields
show UniquePersonList fields
show UniqueEventList fields

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList : persons
AddressBook *--> "1" UniquePersonList : pinnedPersons
AddressBook *--> "1" UniqueEventList : events

UniquePersonList -[hidden]right-> I
UniqueEventList -[hidden]left-> I

@enduml
